# Welcome to Jekyll!
title: SIGCSE 2020
email: webmaster@sigcse2020.org
description: >- # this means to ignore newlines until "baseurl:"
  A site for SIGCSE 2020.
baseurl: "" 
url: ""
twitter_username: sigcse2020
github_username:  sigcsets

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _build/
